# Router Mode Global settings applied to all models unless explicitly overridden
[*]
flash-attn = true
batch-size = 1024
ctx-size = 131072
# KV Cache Quantization parameters
cache-type-k = q4_0
cache-type-v = q4_0
# not more than 2 CPU threads (GPU memory contention)
threads = 2

# General purpose dense model
[qwen38]
hf-repo = unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_XL
# Inherits all global values
temp = 1.0
top-k = 20
top-p = 0.95
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0
# MTP (doubles token generation rate)
spec-type = draft-mtp
spec-draft-n-max = 2
tools = all

# General purpose text and image model
[qwen36]
hf-repo = unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q4_K_M
# Inherits all global values
tools =all

# Google Gemma 4 model profile
[gemma4]
hf-repo = unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q4_K_XL
# Inherits all global values
tools = all

# OCR specialist (Overrides parameters to restrict context and lower temperature)
[LightOn]
hf-repo = staghado/LightOnOCR-2-1B-Q8_0-GGUF
ctx-size = 16384
temp = 0.2
top-k = 0
top-p = 0.9

# Lightweight agent / fast logic model
[qwen35]
hf-repo = unsloth/Qwen3.5-4B-GGUF:UD-Q4_K_XL
ctx-size = 16384
temp = 0.7
top-k = 0
top-p = 0.9
tools = all
